/**
 * Copyright 2018 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// File autogenerated by `helpers/generate_modules/generate_module.py`

module "kubernetes-engine" {
  source = "modules/public-cluster"

  description                       = "${var.description}"
  horizontal_pod_autoscaling        = "${var.horizontal_pod_autoscaling}"
  http_load_balancing               = "${var.http_load_balancing}"
  ip_masq_link_local                = "${var.ip_masq_link_local}"
  ip_masq_resync_interval           = "${var.ip_masq_resync_interval}"
  ip_range_pods                     = "${var.ip_range_pods}"
  ip_range_services                 = "${var.ip_range_services}"
  kubernetes_dashboard              = "${var.kubernetes_dashboard}"
  kubernetes_version                = "${var.kubernetes_version}"
  logging_service                   = "${var.logging_service}"
  maintenance_start_time            = "${var.maintenance_start_time}"
  master_authorized_networks_config = "${var.master_authorized_networks_config}"
  monitoring_service                = "${var.monitoring_service}"
  name                              = "${var.name}"
  network                           = "${var.network}"
  network_policy                    = "${var.network_policy}"
  network_project_id                = "${var.network_project_id}"
  node_pools                        = "${var.node_pools}"
  node_pools_labels                 = "${var.node_pools_labels}"
  node_pools_metadata               = "${var.node_pools_metadata}"
  node_pools_tags                   = "${var.node_pools_tags}"
  node_pools_taints                 = "${var.node_pools_taints}"
  node_version                      = "${var.node_version}"
  non_masquerade_cidrs              = "${var.non_masquerade_cidrs}"
  project_id                        = "${var.project_id}"
  region                            = "${var.region}"
  regional                          = "${var.regional}"
  remove_default_node_pool          = "${var.remove_default_node_pool}"
  service_account                   = "${var.service_account}"
  stub_domains                      = "${var.stub_domains}"
  subnetwork                        = "${var.subnetwork}"
  zones                             = "${var.zones}"
}
