/**
 * Copyright 2018 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// File autogenerated by `helpers/generate_modules/generate_module.py`

output "ca_certificate" {
  value       = "${module.kubernetes-engine.ca_certificate}"
  description = "Cluster ca certificate (base64 encoded)"
}

output "endpoint" {
  value       = "${module.kubernetes-engine.endpoint}"
  description = "Cluster endpoint"
}

output "horizontal_pod_autoscaling_enabled" {
  value       = "${module.kubernetes-engine.horizontal_pod_autoscaling_enabled}"
  description = "Whether horizontal pod autoscaling enabled"
}

output "http_load_balancing_enabled" {
  value       = "${module.kubernetes-engine.http_load_balancing_enabled}"
  description = "Whether http load balancing enabled"
}

output "kubernetes_dashboard_enabled" {
  value       = "${module.kubernetes-engine.kubernetes_dashboard_enabled}"
  description = "Whether kubernetes dashboard enabled"
}

output "location" {
  value       = "${module.kubernetes-engine.location}"
  description = "Cluster location (region if regional cluster, zone if zonal cluster)"
}

output "logging_service" {
  value       = "${module.kubernetes-engine.logging_service}"
  description = "Logging service used"
}

output "master_authorized_networks_config" {
  value       = "${module.kubernetes-engine.master_authorized_networks_config}"
  description = "Networks from which access to master is permitted"
}

output "master_version" {
  value       = "${module.kubernetes-engine.master_version}"
  description = "Current master kubernetes version"
}

output "min_master_version" {
  value       = "${module.kubernetes-engine.min_master_version}"
  description = "Minimum master kubernetes version"
}

output "monitoring_service" {
  value       = "${module.kubernetes-engine.monitoring_service}"
  description = "Monitoring service used"
}

output "name" {
  value       = "${module.kubernetes-engine.name}"
  description = "Cluster name"
}

output "network_policy_enabled" {
  value       = "${module.kubernetes-engine.network_policy_enabled}"
  description = "Whether network policy enabled"
}

output "node_pools_names" {
  value       = "${module.kubernetes-engine.node_pools_names}"
  description = "List of node pools names"
}

output "node_pools_versions" {
  value       = "${module.kubernetes-engine.node_pools_versions}"
  description = "List of node pools versions"
}

output "region" {
  value       = "${module.kubernetes-engine.region}"
  description = "Cluster region"
}

output "type" {
  value       = "${module.kubernetes-engine.type}"
  description = "Cluster type (regional / zonal)"
}

output "zones" {
  value       = "${module.kubernetes-engine.zones}"
  description = "List of zones in which the cluster resides"
}
