# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-kubernetes-engine-workload-identity
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-workload-identity
    source:
      repo: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine.git
      sourceType: git
      dir: /modules/workload-identity
    version: 41.0.2
    actuationTool:
      flavor: Terraform
      version: ">= 1.3"
    description: {}
  content:
    examples:
      - name: autopilot_private_firewalls
        location: examples/autopilot_private_firewalls
      - name: confidential_autopilot_private
        location: examples/confidential_autopilot_private
      - name: confidential_safer_cluster
        location: examples/confidential_safer_cluster
      - name: deploy_service
        location: examples/deploy_service
      - name: disable_client_cert
        location: examples/disable_client_cert
      - name: gke_autopilot_cluster
        location: examples/gke_autopilot_cluster
      - name: gke_standard_cluster
        location: examples/gke_standard_cluster
      - name: island_cluster_anywhere_in_gcp_design
        location: examples/island_cluster_anywhere_in_gcp_design
      - name: island_cluster_with_vm_router
        location: examples/island_cluster_with_vm_router
      - name: node_pool
        location: examples/node_pool
      - name: node_pool_update_variant
        location: examples/node_pool_update_variant
      - name: node_pool_update_variant_beta
        location: examples/node_pool_update_variant_beta
      - name: node_pool_update_variant_public_beta
        location: examples/node_pool_update_variant_public_beta
      - name: private_zonal_with_networking
        location: examples/private_zonal_with_networking
      - name: regional_private_node_pool_oauth_scopes
        location: examples/regional_private_node_pool_oauth_scopes
      - name: safer_cluster
        location: examples/safer_cluster
      - name: safer_cluster_iap_bastion
        location: examples/safer_cluster_iap_bastion
      - name: shared_vpc
        location: examples/shared_vpc
      - name: simple_autopilot_private
        location: examples/simple_autopilot_private
      - name: simple_autopilot_private_cmek
        location: examples/simple_autopilot_private_cmek
      - name: simple_autopilot_private_non_default_sa
        location: examples/simple_autopilot_private_non_default_sa
      - name: simple_autopilot_public
        location: examples/simple_autopilot_public
      - name: simple_fleet_app_operator_permissions
        location: examples/simple_fleet_app_operator_permissions
      - name: simple_regional
        location: examples/simple_regional
      - name: simple_regional_beta
        location: examples/simple_regional_beta
      - name: simple_regional_cluster_autoscaling
        location: examples/simple_regional_cluster_autoscaling
      - name: simple_regional_private
        location: examples/simple_regional_private
      - name: simple_regional_private_beta
        location: examples/simple_regional_private_beta
      - name: simple_regional_private_with_cluster_version
        location: examples/simple_regional_private_with_cluster_version
      - name: simple_regional_with_gateway_api
        location: examples/simple_regional_with_gateway_api
      - name: simple_regional_with_ipv6
        location: examples/simple_regional_with_ipv6
      - name: simple_regional_with_kubeconfig
        location: examples/simple_regional_with_kubeconfig
      - name: simple_regional_with_networking
        location: examples/simple_regional_with_networking
      - name: simple_windows_node_pool
        location: examples/simple_windows_node_pool
      - name: simple_zonal_private
        location: examples/simple_zonal_private
      - name: simple_zonal_with_hub
        location: examples/simple_zonal_with_hub
      - name: simple_zonal_with_hub_kubeconfig
        location: examples/simple_zonal_with_hub_kubeconfig
      - name: stub_domains
        location: examples/stub_domains
      - name: stub_domains_private
        location: examples/stub_domains_private
      - name: stub_domains_upstream_nameservers
        location: examples/stub_domains_upstream_nameservers
      - name: terraform
        location: examples/acm-terraform-blog-part1/terraform
      - name: terraform
        location: examples/acm-terraform-blog-part2/terraform
      - name: terraform
        location: examples/acm-terraform-blog-part3/terraform
      - name: upstream_nameservers
        location: examples/upstream_nameservers
      - name: workload_identity
        location: examples/workload_identity
      - name: workload_metadata_config
        location: examples/workload_metadata_config
  interfaces:
    variables:
      - name: name
        description: Name for both service accounts. The GCP SA will be truncated to the first 30 chars if necessary.
        varType: string
        required: true
      - name: project_id
        description: GCP project ID
        varType: string
        required: true
      - name: gcp_sa_name
        description: Name for the Google service account; overrides `var.name`.
        varType: string
      - name: use_existing_gcp_sa
        description: Use an existing Google service account instead of creating one
        varType: bool
        defaultValue: false
      - name: cluster_name
        description: Cluster name. Required if using existing KSA.
        varType: string
        defaultValue: ""
      - name: location
        description: Cluster location (region if regional cluster, zone if zonal cluster). Required if using existing KSA.
        varType: string
        defaultValue: ""
      - name: k8s_sa_name
        description: Name for the Kubernetes service account; overrides `var.name`. `cluster_name` and `location` must be set when this input is specified.
        varType: string
      - name: k8s_sa_project_id
        description: GCP project ID of the k8s service account; overrides `var.project_id`.
        varType: string
      - name: namespace
        description: Namespace for the Kubernetes service account
        varType: string
        defaultValue: default
      - name: use_existing_k8s_sa
        description: Use an existing kubernetes service account instead of creating one
        varType: bool
        defaultValue: false
      - name: annotate_k8s_sa
        description: Annotate the kubernetes service account with 'iam.gke.io/gcp-service-account' annotation. Valid in cases when an existing SA is used.
        varType: bool
        defaultValue: true
      - name: automount_service_account_token
        description: Enable automatic mounting of the service account token
        varType: bool
        defaultValue: false
      - name: image_pull_secrets
        description: A list of references to secrets in the same namespace to use for pulling any images in pods that reference this Service Account
        varType: list(string)
        defaultValue: []
      - name: roles
        description: A list of roles to be added to the created service account
        varType: list(string)
        defaultValue: []
      - name: impersonate_service_account
        description: An optional service account to impersonate for gcloud commands. If this service account is not specified, the module will use Application Default Credentials.
        varType: string
        defaultValue: ""
      - name: use_existing_context
        description: An optional flag to use local kubectl config context.
        varType: bool
        defaultValue: false
      - name: module_depends_on
        description: List of modules or resources to depend on before annotating KSA. If multiple, all items must be the same type.
        varType: list(any)
        defaultValue: []
      - name: additional_projects
        description: A list of roles to be added to the created service account for additional projects
        varType: map(list(string))
        defaultValue: {}
      - name: gcp_sa_display_name
        description: The Google service account display name; if null, a default string will be used
        varType: string
      - name: gcp_sa_description
        description: The Service Google service account desciption; if null, will be left out
        varType: string
      - name: gcp_sa_create_ignore_already_exists
        description: If set to true, skip service account creation if a service account with the same email already exists.
        varType: bool
    outputs:
      - name: gcp_service_account
        description: GCP service account.
      - name: gcp_service_account_email
        description: Email address of GCP service account.
      - name: gcp_service_account_fqn
        description: FQN of GCP service account.
      - name: gcp_service_account_name
        description: Name of GCP service account.
      - name: k8s_service_account_name
        description: Name of k8s service account.
      - name: k8s_service_account_namespace
        description: Namespace of k8s service account.
  requirements:
    roles:
      - level: Project
        roles:
          - roles/editor
    providerVersions:
      - source: hashicorp/google
        version: ">= 5.12.0, < 8"
      - source: hashicorp/kubernetes
        version: ~> 2.13
