# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-kubernetes-engine-gke-autopilot-cluster-display
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: GKE Autopilot Cluster
    source:
      repo: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine.git
      sourceType: git
      dir: /modules/gke-autopilot-cluster
  ui:
    input:
      variables:
        addons_config:
          name: addons_config
          title: Addons Config
        allow_net_admin:
          name: allow_net_admin
          title: Allow Net Admin
        authenticator_groups_config:
          name: authenticator_groups_config
          title: Authenticator Groups Config
          properties:
            security_group:
              name: security_group
              title: Security Group
              regexValidation: ^gke-security-groups@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$
              validation: Please use a valid email address with the gke-security-groups prefix.
        binary_authorization:
          name: binary_authorization
          title: Binary Authorization
          properties:
            evaluation_mode:
              name: evaluation_mode
              title: Evaluation Mode
              enumValueLabels:
                - label: PROJECT_SINGLETON_POLICY_ENFORCE
                  value: PROJECT_SINGLETON_POLICY_ENFORCE
                - label: DISABLED
                  value: DISABLED
        cluster_autoscaling:
          name: cluster_autoscaling
          title: Cluster Autoscaling
        cluster_ipv4_cidr:
          name: cluster_ipv4_cidr
          title: Cluster Ipv4 Cidr
        cluster_telemetry:
          name: cluster_telemetry
          title: Cluster Telemetry
          properties:
            type:
              name: type
              title: Type
              enumValueLabels:
                - label: ENABLED
                  value: ENABLED
                - label: DISABLED
                  value: DISABLED
                - label: SYSTEM_ONLY
                  value: SYSTEM_ONLY
        confidential_nodes:
          name: confidential_nodes
          title: Confidential Nodes
        control_plane_endpoints_config:
          name: control_plane_endpoints_config
          title: Control Plane Endpoints Config
        cost_management_config:
          name: cost_management_config
          title: Cost Management Config
        database_encryption:
          name: database_encryption
          title: Database Encryption
          properties:
            state:
              name: state
              title: State
              enumValueLabels:
                - label: ENCRYPTED
                  value: ENCRYPTED
                - label: DECRYPTED
                  value: DECRYPTED
        datapath_provider:
          name: datapath_provider
          title: Datapath Provider
          enumValueLabels:
            - label: LEGACY_DATAPATH
              value: LEGACY_DATAPATH
            - label: ADVANCED_DATAPATH
              value: ADVANCED_DATAPATH
          altDefaults:
            - type: ALTERNATE_TYPE_DC
              value: LEGACY_DATAPATH
        default_snat_status:
          name: default_snat_status
          title: Default Snat Status
        deletion_protection:
          name: deletion_protection
          title: Deletion Protection
        description:
          name: description
          title: Description
        disable_l4_lb_firewall_reconciliation:
          name: disable_l4_lb_firewall_reconciliation
          title: Disable L4 Lb Firewall Reconciliation
        dns_config:
          name: dns_config
          title: Dns Config
          properties:
            cluster_dns:
              name: cluster_dns
              title: Cluster Dns
              enumValueLabels:
                - label: CLOUD_DNS
                  value: CLOUD_DNS
                - label: PLATFORM_DEFAULT
                  value: PLATFORM_DEFAULT
        enable_cilium_clusterwide_network_policy:
          name: enable_cilium_clusterwide_network_policy
          title: Enable Cilium Clusterwide Network Policy
        enable_fqdn_network_policy:
          name: enable_fqdn_network_policy
          title: Enable Fqdn Network Policy
        enable_k8s_beta_apis:
          name: enable_k8s_beta_apis
          title: Enable K8s Beta Apis
        enable_l4_ilb_subsetting:
          name: enable_l4_ilb_subsetting
          title: Enable L4 Ilb Subsetting
        enable_multi_networking:
          name: enable_multi_networking
          title: Enable Multi Networking
        enterprise_config:
          name: enterprise_config
          title: Enterprise Config
          properties:
            desired_tier:
              name: desired_tier
              title: Desired Tier
              enumValueLabels:
                - label: STANDARD
                  value: STANDARD
                - label: ENTERPRISE
                  value: ENTERPRISE
        fleet:
          name: fleet
          title: Fleet
        gateway_api_config:
          name: gateway_api_config
          title: Gateway Api Config
          properties:
            channel:
              name: channel
              title: Channel
              enumValueLabels:
                - label: CHANNEL_DISABLED
                  value: CHANNEL_DISABLED
                - label: CHANNEL_EXPERIMENTAL
                  value: CHANNEL_EXPERIMENTAL
                - label: CHANNEL_STANDARD
                  value: CHANNEL_STANDARD
        identity_service_config:
          name: identity_service_config
          title: Identity Service Config
        in_transit_encryption_config:
          name: in_transit_encryption_config
          title: In Transit Encryption Config
          enumValueLabels:
            - label: IN_TRANSIT_ENCRYPTION_DISABLED
              value: IN_TRANSIT_ENCRYPTION_DISABLED
            - label: IN_TRANSIT_ENCRYPTION_INTER_NODE_TRANSPARENT
              value: IN_TRANSIT_ENCRYPTION_INTER_NODE_TRANSPARENT
        ip_allocation_policy:
          name: ip_allocation_policy
          title: Ip Allocation Policy
          properties:
            stack_type:
              name: stack_type
              title: Stack Type
              enumValueLabels:
                - label: IPV4
                  value: IPV4
                - label: IPV4_IPV6
                  value: IPV4_IPV6
        location:
          name: location
          title: Location
        logging_config:
          name: logging_config
          title: Logging Config
          properties:
            enable_components:
              name: enable_components
              title: Enable Components
              enumValueLabels:
                - label: SYSTEM_COMPONENTS
                  value: SYSTEM_COMPONENTS
                - label: APISERVER
                  value: APISERVER
                - label: CONTROLLER_MANAGER
                  value: CONTROLLER_MANAGER
                - label: SCHEDULER
                  value: SCHEDULER
                - label: WORKLOADS
                  value: WORKLOADS
        maintenance_policy:
          name: maintenance_policy
          title: Maintenance Policy
          properties:
            maintenance_exclusion:
              name: maintenance_exclusion
              title: Maintenance Exclusion
              properties:
                exclusion_options:
                  name: exclusion_options
                  title: Exclusion Options
                  properties:
                    scope:
                      name: scope
                      title: Scope
                      enumValueLabels:
                        - label: NO_UPGRADES
                          value: NO_UPGRADES
                        - label: NO_MINOR_UPGRADES
                          value: NO_MINOR_UPGRADES
                        - label: NO_MINOR_OR_NODE_UPGRADES
                          value: NO_MINOR_OR_NODE_UPGRADES
            recurring_window:
              name: recurring_window
              title: Recurring Window
              properties:
                recurrence:
                  name: recurrence
                  title: Recurrence
                  regexValidation: ^(FREQ|BYDAY|BYMONTHDAY|BYMONTH|BYYEARDAY|INTERVAL|COUNT|UNTIL|WKST|BYSETPOS|BYWEEKNO|BYHOUR|BYMINUTE|BYSECOND|RRULE|DTSTART|TZID|RDATE|EXDATE|EXRULE|ACTION|ATTENDEE|CALSCALE|CATEGORIES|CLASS|COMMENT|CONTACT|CREATED|DESCRIPTION|GEO|LAST-MODIFIED|LOCATION|ORGANIZER|PRIORITY|SEQUENCE|STATUS|SUMMARY|TRANSP|URL|UID|VERSION|PRODID|X-PUBLISHED-TTL|X-WR-CALNAME|X-WR-CALDESC|X-WR-TIMEZONE|X-WR-RECURID)$
                  validation: The recurrence field should be a valid RFC 5545 recurrence rule.
        master_auth:
          name: master_auth
          title: Master Auth
        master_authorized_networks_config:
          name: master_authorized_networks_config
          title: Master Authorized Networks Config
          properties:
            cidr_blocks:
              name: cidr_blocks
              title: Cidr Blocks
              properties:
                cidr_block:
                  name: cidr_block
                  title: Cidr Block
                  regexValidation: ^((((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\/(3[0-2]|[12]?[0-9]))|((s*((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|(([0-9A-Fa-f]{1,4}:){6}(:[0-9A-Fa-f]{1,4}|((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){5}(((:[0-9A-Fa-f]{1,4}){1,2})|:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){4}(((:[0-9A-Fa-f]{1,4}){1,3})|((:[0-9A-Fa-f]{1,4})?:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){3}(((:[0-9A-Fa-f]{1,4}){1,4})|((:[0-9A-Fa-f]{1,4}){0,2}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){2}(((:[0-9A-Fa-f]{1,4}){1,5})|((:[0-9A-Fa-f]{1,4}){0,3}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){1}(((:[0-9A-Fa-f]{1,4}){1,6})|((:[0-9A-Fa-f]{1,4}){0,4}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(:(((:[0-9A-Fa-f]{1,4}){1,7})|((:[0-9A-Fa-f]{1,4}){0,5}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:)))(%.+)?\s*\/(12[0-8]|1[01][0-9]|[1-9]?[0-9]))))$
                  validation: Enter the valid CIDR notation.
        mesh_certificates:
          name: mesh_certificates
          title: Mesh Certificates
        min_master_version:
          name: min_master_version
          title: Min Master Version
        monitoring_config:
          name: monitoring_config
          title: Monitoring Config
          properties:
            enable_components:
              name: enable_components
              title: Enable Components
              enumValueLabels:
                - label: SYSTEM_COMPONENTS
                  value: SYSTEM_COMPONENTS
                - label: APISERVER
                  value: APISERVER
                - label: SCHEDULER
                  value: SCHEDULER
                - label: CONTROLLER_MANAGER
                  value: CONTROLLER_MANAGER
                - label: STORAGE
                  value: STORAGE
                - label: HPA
                  value: HPA
                - label: POD
                  value: POD
                - label: DAEMONSET
                  value: DAEMONSET
                - label: DEPLOYMENT
                  value: DEPLOYMENT
                - label: STATEFULSET
                  value: STATEFULSET
                - label: KUBELET
                  value: KUBELET
                - label: CADVISOR
                  value: CADVISOR
                - label: DCGM
                  value: DCGM
                - label: JOBSET
                  value: JOBSET
        name:
          name: name
          title: Name
          regexValidation: ^[a-z][a-z0-9-]{0,38}[a-z0-9]$
          validation: The cluster name must start with a lowercase letter and can contain up to 40 characters. It can include lowercase letters, numbers, and hyphens, but it cannot end with a hyphen. The name must be unique within its project and location.
        network:
          name: network
          title: Network
          regexValidation: ^[a-z][a-z0-9-]{0,60}[a-z0-9]$
          validation: Network name must start with a lowercase letter followed by up to 62 lowercase letters, numbers, or hyphens and cannot end with a hyphen.
          altDefaults:
            - type: ALTERNATE_TYPE_DC
              value: default
        node_locations:
          name: node_locations
          title: Node Locations
        node_pool_auto_config:
          name: node_pool_auto_config
          title: Node Pool Auto Config
          properties:
            linux_node_config:
              name: linux_node_config
              title: Linux Node Config
              properties:
                cgroup_mode:
                  name: cgroup_mode
                  title: Cgroup Mode
                  enumValueLabels:
                    - label: CGROUP_MODE_UNSPECIFIED
                      value: CGROUP_MODE_UNSPECIFIED
                    - label: CGROUP_MODE_V1
                      value: CGROUP_MODE_V1
                    - label: CGROUP_MODE_V2
                      value: CGROUP_MODE_V2
        notification_config:
          name: notification_config
          title: Notification Config
          properties:
            pubsub:
              name: pubsub
              title: Pubsub
              properties:
                filter:
                  name: filter
                  title: Filter
                  properties:
                    event_type:
                      name: event_type
                      title: Event Type
                      enumValueLabels:
                        - label: UPGRADE_AVAILABLE_EVENT
                          value: UPGRADE_AVAILABLE_EVENT
                        - label: UPGRADE_EVENT
                          value: UPGRADE_EVENT
                        - label: SECURITY_BULLETIN_EVENT
                          value: SECURITY_BULLETIN_EVENT
                        - label: UPGRADE_INFO_EVENT
                          value: UPGRADE_INFO_EVENT
        pod_autoscaling:
          name: pod_autoscaling
          title: Pod Autoscaling
          properties:
            hpa_profile:
              name: hpa_profile
              title: Hpa Profile
              enumValueLabels:
                - label: NONE
                  value: NONE
                - label: PERFORMANCE
                  value: PERFORMANCE
        pod_security_policy_config:
          name: pod_security_policy_config
          title: Pod Security Policy Config
        private_cluster_config:
          name: private_cluster_config
          title: Private Cluster Config
        private_ipv6_google_access:
          name: private_ipv6_google_access
          title: Private Ipv6 Google Access
          enumValueLabels:
            - label: PRIVATE_IPV6_GOOGLE_ACCESS_UNSPECIFIED
              value: PRIVATE_IPV6_GOOGLE_ACCESS_UNSPECIFIED
            - label: PRIVATE_IPV6_GOOGLE_ACCESS_DISABLED
              value: PRIVATE_IPV6_GOOGLE_ACCESS_DISABLED
            - label: PRIVATE_IPV6_GOOGLE_ACCESS_TO_GOOGLE
              value: PRIVATE_IPV6_GOOGLE_ACCESS_TO_GOOGLE
            - label: PRIVATE_IPV6_GOOGLE_ACCESS_BIDIRECTIONAL
              value: PRIVATE_IPV6_GOOGLE_ACCESS_BIDIRECTIONAL
          altDefaults:
            - type: ALTERNATE_TYPE_DC
              value: PRIVATE_IPV6_GOOGLE_ACCESS_UNSPECIFIED
        project_id:
          name: project_id
          title: Project Id
        protect_config:
          name: protect_config
          title: Protect Config
          properties:
            workload_vulnerability_mode:
              name: workload_vulnerability_mode
              title: Workload Vulnerability Mode
              enumValueLabels:
                - label: DISABLED
                  value: DISABLED
                - label: BASIC
                  value: BASIC
        release_channel:
          name: release_channel
          title: Release Channel
          properties:
            channel:
              name: channel
              title: Channel
              enumValueLabels:
                - label: UNSPECIFIED
                  value: UNSPECIFIED
                - label: RAPID
                  value: RAPID
                - label: REGULAR
                  value: REGULAR
                - label: STABLE
                  value: STABLE
                - label: EXTENDED
                  value: EXTENDED
        resource_labels:
          name: resource_labels
          title: Resource Labels
        resource_usage_export_config:
          name: resource_usage_export_config
          title: Resource Usage Export Config
        secret_manager_config:
          name: secret_manager_config
          title: Secret Manager Config
        security_posture_config:
          name: security_posture_config
          title: Security Posture Config
          properties:
            mode:
              name: mode
              title: Mode
              enumValueLabels:
                - label: DISABLED
                  value: DISABLED
                - label: BASIC
                  value: BASIC
                - label: ENTERPRISE
                  value: ENTERPRISE
            vulnerability_mode:
              name: vulnerability_mode
              title: Vulnerability Mode
              enumValueLabels:
                - label: VULNERABILITY_DISABLED
                  value: VULNERABILITY_DISABLED
                - label: VULNERABILITY_BASIC
                  value: VULNERABILITY_BASIC
                - label: VULNERABILITY_ENTERPRISE
                  value: VULNERABILITY_ENTERPRISE
        service_external_ips_config:
          name: service_external_ips_config
          title: Service External Ips Config
        subnetwork:
          name: subnetwork
          title: Subnetwork
          regexValidation: ^[a-z][a-z0-9-]{0,60}[a-z0-9]$
          validation: Network name must start with a lowercase letter followed by up to 62 lowercase letters, numbers, or hyphens and cannot end with a hyphen.
          altDefaults:
            - type: ALTERNATE_TYPE_DC
              value: default
        timeouts:
          name: timeouts
          title: Timeouts
        vertical_pod_autoscaling:
          name: vertical_pod_autoscaling
          title: Vertical Pod Autoscaling
        workload_alts_config:
          name: workload_alts_config
          title: Workload Alts Config
        workload_identity_config:
          name: workload_identity_config
          title: Workload Identity Config
          properties:
            workload_pool:
              name: workload_pool
              title: Workload Pool
              regexValidation: ^.+\.svc\.id\.goog$
              validation: Workload pool must be in the format <project_id>.svc.id.goog.
    runtime:
      outputs:
        cluster_id:
          visibility: VISIBILITY_ROOT
