# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-kubernetes-engine-hub-legacy
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Hub Submodule
    source:
      repo: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine.git
      sourceType: git
      dir: /modules/hub-legacy
    version: 37.1.0
    actuationTool:
      flavor: Terraform
      version: ">= 1.3"
    description: {}
  content:
    examples:
      - name: autopilot_private_firewalls
        location: examples/autopilot_private_firewalls
      - name: confidential_autopilot_private
        location: examples/confidential_autopilot_private
      - name: confidential_safer_cluster
        location: examples/confidential_safer_cluster
      - name: deploy_service
        location: examples/deploy_service
      - name: disable_client_cert
        location: examples/disable_client_cert
      - name: gke_autopilot_cluster
        location: examples/gke_autopilot_cluster
      - name: gke_standard_cluster
        location: examples/gke_standard_cluster
      - name: island_cluster_anywhere_in_gcp_design
        location: examples/island_cluster_anywhere_in_gcp_design
      - name: island_cluster_with_vm_router
        location: examples/island_cluster_with_vm_router
      - name: node_pool
        location: examples/node_pool
      - name: node_pool_update_variant
        location: examples/node_pool_update_variant
      - name: node_pool_update_variant_beta
        location: examples/node_pool_update_variant_beta
      - name: node_pool_update_variant_public_beta
        location: examples/node_pool_update_variant_public_beta
      - name: private_zonal_with_networking
        location: examples/private_zonal_with_networking
      - name: regional_private_node_pool_oauth_scopes
        location: examples/regional_private_node_pool_oauth_scopes
      - name: safer_cluster
        location: examples/safer_cluster
      - name: safer_cluster_iap_bastion
        location: examples/safer_cluster_iap_bastion
      - name: shared_vpc
        location: examples/shared_vpc
      - name: simple_autopilot_private
        location: examples/simple_autopilot_private
      - name: simple_autopilot_private_cmek
        location: examples/simple_autopilot_private_cmek
      - name: simple_autopilot_private_non_default_sa
        location: examples/simple_autopilot_private_non_default_sa
      - name: simple_autopilot_public
        location: examples/simple_autopilot_public
      - name: simple_fleet_app_operator_permissions
        location: examples/simple_fleet_app_operator_permissions
      - name: simple_regional
        location: examples/simple_regional
      - name: simple_regional_beta
        location: examples/simple_regional_beta
      - name: simple_regional_cluster_autoscaling
        location: examples/simple_regional_cluster_autoscaling
      - name: simple_regional_private
        location: examples/simple_regional_private
      - name: simple_regional_private_beta
        location: examples/simple_regional_private_beta
      - name: simple_regional_private_with_cluster_version
        location: examples/simple_regional_private_with_cluster_version
      - name: simple_regional_with_gateway_api
        location: examples/simple_regional_with_gateway_api
      - name: simple_regional_with_ipv6
        location: examples/simple_regional_with_ipv6
      - name: simple_regional_with_kubeconfig
        location: examples/simple_regional_with_kubeconfig
      - name: simple_regional_with_networking
        location: examples/simple_regional_with_networking
      - name: simple_windows_node_pool
        location: examples/simple_windows_node_pool
      - name: simple_zonal_private
        location: examples/simple_zonal_private
      - name: simple_zonal_with_hub
        location: examples/simple_zonal_with_hub
      - name: simple_zonal_with_hub_kubeconfig
        location: examples/simple_zonal_with_hub_kubeconfig
      - name: stub_domains
        location: examples/stub_domains
      - name: stub_domains_private
        location: examples/stub_domains_private
      - name: stub_domains_upstream_nameservers
        location: examples/stub_domains_upstream_nameservers
      - name: terraform
        location: examples/acm-terraform-blog-part1/terraform
      - name: terraform
        location: examples/acm-terraform-blog-part2/terraform
      - name: terraform
        location: examples/acm-terraform-blog-part3/terraform
      - name: upstream_nameservers
        location: examples/upstream_nameservers
      - name: workload_identity
        location: examples/workload_identity
      - name: workload_metadata_config
        location: examples/workload_metadata_config
  interfaces:
    variables:
      - name: cluster_name
        description: The unique name to identify the cluster in ASM.
        varType: string
        required: true
      - name: cluster_endpoint
        description: The GKE cluster endpoint.
        varType: string
        required: true
      - name: project_id
        description: The project in which the resource belongs.
        varType: string
        required: true
      - name: hub_project_id
        description: The project in which the GKE Hub belongs.
        varType: string
        defaultValue: ""
      - name: location
        description: The location (zone or region) this cluster has been created in.
        varType: string
        required: true
      - name: use_tf_google_credentials_env_var
        description: Optional GOOGLE_CREDENTIALS environment variable to be activated.
        varType: bool
        defaultValue: false
      - name: gcloud_sdk_version
        description: The gcloud sdk version to use. Minimum required version is 293.0.0
        varType: string
        defaultValue: 296.0.1
      - name: gke_hub_sa_name
        description: Name for the GKE Hub SA stored as a secret `creds-gcp` in the `gke-connect` namespace.
        varType: string
        defaultValue: gke-hub-sa
      - name: gke_hub_membership_name
        description: Membership name that uniquely represents the cluster being registered on the Hub
        varType: string
        defaultValue: gke-hub-membership
      - name: use_existing_sa
        description: Uses an existing service account to register membership. Requires sa_private_key
        varType: bool
        defaultValue: false
      - name: sa_private_key
        description: Private key for service account base64 encoded. Required only if `use_existing_sa` is set to `true`.
        varType: string
      - name: module_depends_on
        description: List of modules or resources this module depends on.
        varType: list(any)
        defaultValue: []
      - name: use_kubeconfig
        description: Use existing kubeconfig to register membership. Set this to true for non GKE clusters. Assumes kubectl context is set to cluster to register.
        varType: bool
        defaultValue: false
      - name: labels
        description: Comma separated labels in the format name=value to apply to cluster in the GCP Console.
        varType: string
        defaultValue: ""
    outputs:
      - name: wait
        description: An output to use when you want to depend on registration finishing
