# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-kubernetes-engine-gke-standard-cluster-display
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: GKE Standard Cluster
    source:
      repo: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine.git
      sourceType: git
      dir: /modules/gke-standard-cluster
  ui:
    input:
      variables:
        addons_config:
          name: addons_config
          title: Addons Config
        authenticator_groups_config:
          name: authenticator_groups_config
          title: Authenticator Groups Config
        binary_authorization:
          name: binary_authorization
          title: Binary Authorization
        cluster_autoscaling:
          name: cluster_autoscaling
          title: Cluster Autoscaling
        cluster_ipv4_cidr:
          name: cluster_ipv4_cidr
          title: Cluster Ipv4 Cidr
        cluster_telemetry:
          name: cluster_telemetry
          title: Cluster Telemetry
        confidential_nodes:
          name: confidential_nodes
          title: Confidential Nodes
        control_plane_endpoints_config:
          name: control_plane_endpoints_config
          title: Control Plane Endpoints Config
        cost_management_config:
          name: cost_management_config
          title: Cost Management Config
        database_encryption:
          name: database_encryption
          title: Database Encryption
        datapath_provider:
          name: datapath_provider
          title: Datapath Provider
          altDefaults:
            - type: ALTERNATE_TYPE_DC
              value: LEGACY_DATAPATH
        default_max_pods_per_node:
          name: default_max_pods_per_node
          title: Default Max Pods Per Node
        default_snat_status:
          name: default_snat_status
          title: Default Snat Status
        deletion_protection:
          name: deletion_protection
          title: Deletion Protection
        description:
          name: description
          title: Description
        disable_l4_lb_firewall_reconciliation:
          name: disable_l4_lb_firewall_reconciliation
          title: Disable L4 Lb Firewall Reconciliation
        dns_config:
          name: dns_config
          title: Dns Config
        enable_cilium_clusterwide_network_policy:
          name: enable_cilium_clusterwide_network_policy
          title: Enable Cilium Clusterwide Network Policy
        enable_fqdn_network_policy:
          name: enable_fqdn_network_policy
          title: Enable Fqdn Network Policy
        enable_intranode_visibility:
          name: enable_intranode_visibility
          title: Enable Intranode Visibility
        enable_k8s_beta_apis:
          name: enable_k8s_beta_apis
          title: Enable K8s Beta Apis
        enable_kubernetes_alpha:
          name: enable_kubernetes_alpha
          title: Enable Kubernetes Alpha
        enable_l4_ilb_subsetting:
          name: enable_l4_ilb_subsetting
          title: Enable L4 Ilb Subsetting
        enable_legacy_abac:
          name: enable_legacy_abac
          title: Enable Legacy Abac
        enable_multi_networking:
          name: enable_multi_networking
          title: Enable Multi Networking
        enable_shielded_nodes:
          name: enable_shielded_nodes
          title: Enable Shielded Nodes
        enable_tpu:
          name: enable_tpu
          title: Enable Tpu
        enterprise_config:
          name: enterprise_config
          title: Enterprise Config
        fleet:
          name: fleet
          title: Fleet
        gateway_api_config:
          name: gateway_api_config
          title: Gateway Api Config
        identity_service_config:
          name: identity_service_config
          title: Identity Service Config
        in_transit_encryption_config:
          name: in_transit_encryption_config
          title: In Transit Encryption Config
        initial_node_count:
          name: initial_node_count
          title: Initial Node Count
          altDefaults:
            - type: ALTERNATE_TYPE_DC
              value: 1
        ip_allocation_policy:
          name: ip_allocation_policy
          title: Ip Allocation Policy
        location:
          name: location
          title: Location
        logging_config:
          name: logging_config
          title: Logging Config
        logging_service:
          name: logging_service
          title: Logging Service
        maintenance_policy:
          name: maintenance_policy
          title: Maintenance Policy
        master_auth:
          name: master_auth
          title: Master Auth
        master_authorized_networks_config:
          name: master_authorized_networks_config
          title: Master Authorized Networks Config
          altDefaults:
            - type: ALTERNATE_TYPE_DC
              value:
                private_endpoint_enforcement_enabled: true
        mesh_certificates:
          name: mesh_certificates
          title: Mesh Certificates
        min_master_version:
          name: min_master_version
          title: Min Master Version
        monitoring_config:
          name: monitoring_config
          title: Monitoring Config
        monitoring_service:
          name: monitoring_service
          title: Monitoring Service
        name:
          name: name
          title: Name
        network:
          name: network
          title: Network
        network_policy:
          name: network_policy
          title: Network Policy
        node_config:
          name: node_config
          title: Node Config
        node_locations:
          name: node_locations
          title: Node Locations
        node_pool:
          name: node_pool
          title: Node Pool
        node_pool_auto_config:
          name: node_pool_auto_config
          title: Node Pool Auto Config
        node_pool_defaults:
          name: node_pool_defaults
          title: Node Pool Defaults
        node_version:
          name: node_version
          title: Node Version
        notification_config:
          name: notification_config
          title: Notification Config
        pod_autoscaling:
          name: pod_autoscaling
          title: Pod Autoscaling
        pod_security_policy_config:
          name: pod_security_policy_config
          title: Pod Security Policy Config
        private_cluster_config:
          name: private_cluster_config
          title: Private Cluster Config
        private_ipv6_google_access:
          name: private_ipv6_google_access
          title: Private Ipv6 Google Access
          altDefaults:
            - type: ALTERNATE_TYPE_DC
              value: PRIVATE_IPV6_GOOGLE_ACCESS_UNSPECIFIED
        project:
          name: project
          title: Project
        protect_config:
          name: protect_config
          title: Protect Config
        release_channel:
          name: release_channel
          title: Release Channel
        remove_default_node_pool:
          name: remove_default_node_pool
          title: Remove Default Node Pool
        resource_labels:
          name: resource_labels
          title: Resource Labels
        resource_usage_export_config:
          name: resource_usage_export_config
          title: Resource Usage Export Config
        secret_manager_config:
          name: secret_manager_config
          title: Secret Manager Config
        security_posture_config:
          name: security_posture_config
          title: Security Posture Config
        service_external_ips_config:
          name: service_external_ips_config
          title: Service External Ips Config
        subnetwork:
          name: subnetwork
          title: Subnetwork
        timeouts:
          name: timeouts
          title: Timeouts
        vertical_pod_autoscaling:
          name: vertical_pod_autoscaling
          title: Vertical Pod Autoscaling
        workload_alts_config:
          name: workload_alts_config
          title: Workload Alts Config
        workload_identity_config:
          name: workload_identity_config
          title: Workload Identity Config
